import './globals.css'
import { Inter } from 'next/font/google'
import Footer from './footer/page'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Capstone Project',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
    
    <html lang="en">
    <body className={inter.className}>

        {children}
        <Footer/>
        </body>
      
    </html>
    </>

  )
}
